

const gdCityDistrictList = [{
    "id": 1,
    "name": "广州",
    "parentId": 0,
    "districts": [{
        "id": 101,
        "name": "白云区",
        "parentId": 1
    }, {
        "id": 102,
        "name": "从化区",
        "parentId": 1
    }, {
        "id": 103,
        "name": "番禺区",
        "parentId": 1
    }, {
        "id": 104,
        "name": "海珠区",
        "parentId": 1
    }, {
        "id": 105,
        "name": "花都区",
        "parentId": 1
    }, {
        "id": 106,
        "name": "黄埔区",
        "parentId": 1
    }, {
        "id": 107,
        "name": "荔湾区",
        "parentId": 1
    }, {
        "id": 108,
        "name": "南沙区",
        "parentId": 1
    }, {
        "id": 109,
        "name": "天河区",
        "parentId": 1
    }, {
        "id": 110,
        "name": "越秀区",
        "parentId": 1
    }, {
        "id": 111,
        "name": "增城区",
        "parentId": 1
    }]
}, {
    "id": 2,
    "name": "深圳",
    "parentId": 0,
    "districts": [{
        "id": 201,
        "name": "宝安区",
        "parentId": 2
    }, {
        "id": 202,
        "name": "福田区",
        "parentId": 2
    }, {
        "id": 203,
        "name": "龙岗区",
        "parentId": 2
    }, {
        "id": 204,
        "name": "罗湖区",
        "parentId": 2
    }, {
        "id": 205,
        "name": "南山区",
        "parentId": 2
    }, {
        "id": 206,
        "name": "盐田区",
        "parentId": 2
    }, {
        "id": 207,
        "name": "龙华区",
        "parentId": 2
    }, {
        "id": 208,
        "name": "光明新区",
        "parentId": 2
    }, {
        "id": 209,
        "name": "坪山区",
        "parentId": 2
    }]
}, {
    "id": 3,
    "name": "珠海",
    "parentId": 0,
    "districts": [{
        "id": 301,
        "name": "斗门区",
        "parentId": 3
    }, {
        "id": 302,
        "name": "阜宁县",
        "parentId": 3
    }, {
        "id": 303,
        "name": "金湾区",
        "parentId": 3
    }, {
        "id": 304,
        "name": "香洲区",
        "parentId": 3
    }]
}, {
    "id": 4,
    "name": "汕头",
    "parentId": 0,
    "districts": [{
        "id": 401,
        "name": "潮南区",
        "parentId": 4
    }, {
        "id": 402,
        "name": "潮阳区",
        "parentId": 4
    }, {
        "id": 403,
        "name": "澄海区",
        "parentId": 4
    }, {
        "id": 404,
        "name": "江南区",
        "parentId": 4
    }, {
        "id": 405,
        "name": "金平区",
        "parentId": 4
    }, {
        "id": 406,
        "name": "龙湖区",
        "parentId": 4
    }, {
        "id": 407,
        "name": "南澳县",
        "parentId": 4
    }, {
        "id": 408,
        "name": "濠江区",
        "parentId": 4
    }]
}, {
    "id": 5,
    "name": "韶关",
    "parentId": 0,
    "districts": [{
        "id": 503,
        "name": "乐昌市",
        "parentId": 5
    }, {
        "id": 505,
        "name": "南雄市",
        "parentId": 5
    }, {
        "id": 506,
        "name": "曲江区",
        "parentId": 5
    }, {
        "id": 508,
        "name": "仁化县",
        "parentId": 5
    }, {
        "id": 509,
        "name": "乳源瑶族自治县",
        "parentId": 5
    }, {
        "id": 510,
        "name": "始兴县",
        "parentId": 5
    }, {
        "id": 511,
        "name": "翁源县",
        "parentId": 5
    }, {
        "id": 512,
        "name": "武江区",
        "parentId": 5
    }, {
        "id": 513,
        "name": "新丰县",
        "parentId": 5
    }, {
        "id": 515,
        "name": "浈江区",
        "parentId": 5
    }]
}, {
    "id": 6,
    "name": "河源",
    "parentId": 0,
    "districts": [{
        "id": 601,
        "name": "东源县",
        "parentId": 6
    }, {
        "id": 602,
        "name": "和平县",
        "parentId": 6
    }, {
        "id": 603,
        "name": "连平县",
        "parentId": 6
    }, {
        "id": 604,
        "name": "龙川县",
        "parentId": 6
    }, {
        "id": 605,
        "name": "源城区",
        "parentId": 6
    }, {
        "id": 606,
        "name": "紫金县",
        "parentId": 6
    }]
}, {
    "id": 7,
    "name": "梅州",
    "parentId": 0,
    "districts": [{
        "id": 701,
        "name": "大埔县",
        "parentId": 7
    }, {
        "id": 702,
        "name": "丰顺县",
        "parentId": 7
    }, {
        "id": 703,
        "name": "蕉岭县",
        "parentId": 7
    }, {
        "id": 704,
        "name": "梅江区",
        "parentId": 7
    }, {
        "id": 705,
        "name": "梅县区",
        "parentId": 7
    }, {
        "id": 706,
        "name": "平远县",
        "parentId": 7
    }, {
        "id": 707,
        "name": "五华县",
        "parentId": 7
    }, {
        "id": 708,
        "name": "兴宁市",
        "parentId": 7
    }]
}, {
    "id": 8,
    "name": "惠州",
    "parentId": 0,
    "districts": [{
        "id": 801,
        "name": "博罗县",
        "parentId": 8
    }, {
        "id": 802,
        "name": "惠城区",
        "parentId": 8
    }, {
        "id": 803,
        "name": "惠东县",
        "parentId": 8
    }, {
        "id": 804,
        "name": "惠阳区",
        "parentId": 8
    }, {
        "id": 805,
        "name": "龙门县",
        "parentId": 8
    }]
}, {
    "id": 9,
    "name": "汕尾",
    "parentId": 0,
    "districts": [{
        "id": 901,
        "name": "城区",
        "parentId": 9
    }, {
        "id": 902,
        "name": "海丰县",
        "parentId": 9
    }, {
        "id": 903,
        "name": "陆丰市",
        "parentId": 9
    }, {
        "id": 904,
        "name": "陆河县",
        "parentId": 9
    }]
}, {
    "id": 10,
    "name": "东莞",
    "parentId": 0,
    "districts": [{
        "id": 1001,
        "name": "茶山镇",
        "parentId": 10
    }, {
        "id": 1002,
        "name": "常平镇",
        "parentId": 10
    }, {
        "id": 1003,
        "name": "长安镇",
        "parentId": 10
    }, {
        "id": 1004,
        "name": "大朗镇",
        "parentId": 10
    }, {
        "id": 1005,
        "name": "大岭山镇",
        "parentId": 10
    }, {
        "id": 1006,
        "name": "道滘镇",
        "parentId": 10
    }, {
        "id": 1007,
        "name": "东城街道",
        "parentId": 10
    }, {
        "id": 1009,
        "name": "东坑镇",
        "parentId": 10
    }, {
        "id": 1011,
        "name": "凤岗镇",
        "parentId": 10
    }, {
        "id": 1012,
        "name": "高埗镇",
        "parentId": 10
    }, {
        "id": 1013,
        "name": "横沥镇",
        "parentId": 10
    }, {
        "id": 1014,
        "name": "洪梅镇",
        "parentId": 10
    }, {
        "id": 1015,
        "name": "厚街镇",
        "parentId": 10
    }, {
        "id": 1016,
        "name": "虎门镇",
        "parentId": 10
    }, {
        "id": 1017,
        "name": "黄江镇",
        "parentId": 10
    }, {
        "id": 1019,
        "name": "麻涌镇",
        "parentId": 10
    }, {
        "id": 1020,
        "name": "南城街道",
        "parentId": 10
    }, {
        "id": 1021,
        "name": "企石镇",
        "parentId": 10
    }, {
        "id": 1022,
        "name": "桥头镇",
        "parentId": 10
    }, {
        "id": 1023,
        "name": "清溪镇",
        "parentId": 10
    }, {
        "id": 1024,
        "name": "沙田镇",
        "parentId": 10
    }, {
        "id": 1025,
        "name": "石龙镇",
        "parentId": 10
    }, {
        "id": 1027,
        "name": "石排镇",
        "parentId": 10
    }, {
        "id": 1028,
        "name": "石碣镇",
        "parentId": 10
    }, {
        "id": 1029,
        "name": "松山湖管委会",
        "parentId": 10
    }, {
        "id": 1030,
        "name": "塘厦镇",
        "parentId": 10
    }, {
        "id": 1031,
        "name": "万江街道",
        "parentId": 10
    }, {
        "id": 1033,
        "name": "望牛墩镇",
        "parentId": 10
    }, {
        "id": 1034,
        "name": "谢岗镇",
        "parentId": 10
    }, {
        "id": 1035,
        "name": "樟木头镇",
        "parentId": 10
    }, {
        "id": 1036,
        "name": "中堂镇",
        "parentId": 10
    }, {
        "id": 1037,
        "name": "莞城街道",
        "parentId": 10
    }, {
        "id": 1038,
        "name": "寮步镇",
        "parentId": 10
    }]
}, {
    "id": 11,
    "name": "中山",
    "parentId": 0,
    "districts": [{
        "id": 1101,
        "name": "板芙镇",
        "parentId": 11
    }, {
        "id": 1102,
        "name": "大涌镇",
        "parentId": 11
    }, {
        "id": 1103,
        "name": "东凤镇",
        "parentId": 11
    }, {
        "id": 1104,
        "name": "东区街道",
        "parentId": 11
    }, {
        "id": 1105,
        "name": "东升镇",
        "parentId": 11
    }, {
        "id": 1106,
        "name": "阜沙镇",
        "parentId": 11
    }, {
        "id": 1107,
        "name": "港口镇",
        "parentId": 11
    }, {
        "id": 1108,
        "name": "古镇镇",
        "parentId": 11
    }, {
        "id": 1109,
        "name": "横栏镇",
        "parentId": 11
    }, {
        "id": 1110,
        "name": "黄圃镇",
        "parentId": 11
    }, {
        "id": 1111,
        "name": "火炬开发区街道",
        "parentId": 11
    }, {
        "id": 1112,
        "name": "民众镇",
        "parentId": 11
    }, {
        "id": 1113,
        "name": "南朗镇",
        "parentId": 11
    }, {
        "id": 1115,
        "name": "南区街道",
        "parentId": 11
    }, {
        "id": 1116,
        "name": "南头镇",
        "parentId": 11
    }, {
        "id": 1117,
        "name": "三角镇",
        "parentId": 11
    }, {
        "id": 1118,
        "name": "三乡镇",
        "parentId": 11
    }, {
        "id": 1119,
        "name": "沙溪镇",
        "parentId": 11
    }, {
        "id": 1120,
        "name": "神湾镇",
        "parentId": 11
    }, {
        "id": 1121,
        "name": "石岐区街道",
        "parentId": 11
    }, {
        "id": 1122,
        "name": "坦洲镇",
        "parentId": 11
    }, {
        "id": 1123,
        "name": "五桂山街道",
        "parentId": 11
    }, {
        "id": 1124,
        "name": "西区街道",
        "parentId": 11
    }, {
        "id": 1125,
        "name": "小榄镇",
        "parentId": 11
    }, {
        "id": 1127,
        "name": "沙朗镇",
        "parentId": 11
    }]
}, {
    "id": 12,
    "name": "江门",
    "parentId": 0,
    "districts": [{
        "id": 1201,
        "name": "恩平市",
        "parentId": 12
    }, {
        "id": 1202,
        "name": "鹤山市",
        "parentId": 12
    }, {
        "id": 1203,
        "name": "江海区",
        "parentId": 12
    }, {
        "id": 1204,
        "name": "开平市",
        "parentId": 12
    }, {
        "id": 1205,
        "name": "蓬江区",
        "parentId": 12
    }, {
        "id": 1206,
        "name": "台山市",
        "parentId": 12
    }, {
        "id": 1207,
        "name": "新会区",
        "parentId": 12
    }]
}, {
    "id": 13,
    "name": "佛山",
    "parentId": 0,
    "districts": [{
        "id": 1301,
        "name": "高明区",
        "parentId": 13
    }, {
        "id": 1302,
        "name": "南海区",
        "parentId": 13
    }, {
        "id": 1303,
        "name": "三水区",
        "parentId": 13
    }, {
        "id": 1304,
        "name": "顺德区",
        "parentId": 13
    }, {
        "id": 1305,
        "name": "禅城区",
        "parentId": 13
    }]
}, {
    "id": 14,
    "name": "阳江",
    "parentId": 0,
    "districts": [{
        "id": 1401,
        "name": "江城区",
        "parentId": 14
    }, {
        "id": 1402,
        "name": "阳春市",
        "parentId": 14
    }, {
        "id": 1403,
        "name": "阳东区",
        "parentId": 14
    }, {
        "id": 1404,
        "name": "阳西县",
        "parentId": 14
    }]
}, {
    "id": 15,
    "name": "湛江",
    "parentId": 0,
    "districts": [{
        "id": 1501,
        "name": "赤坎区",
        "parentId": 15
    }, {
        "id": 1502,
        "name": "雷州市",
        "parentId": 15
    }, {
        "id": 1503,
        "name": "廉江市",
        "parentId": 15
    }, {
        "id": 1504,
        "name": "麻章区",
        "parentId": 15
    }, {
        "id": 1505,
        "name": "坡头区",
        "parentId": 15
    }, {
        "id": 1506,
        "name": "遂溪县",
        "parentId": 15
    }, {
        "id": 1507,
        "name": "吴川市",
        "parentId": 15
    }, {
        "id": 1508,
        "name": "霞山区",
        "parentId": 15
    }, {
        "id": 1509,
        "name": "徐闻县",
        "parentId": 15
    }]
}, {
    "id": 16,
    "name": "茂名",
    "parentId": 0,
    "districts": [{
        "id": 1601,
        "name": "电白区",
        "parentId": 16
    }, {
        "id": 1602,
        "name": "高州市",
        "parentId": 16
    }, {
        "id": 1603,
        "name": "化州市",
        "parentId": 16
    }, {
        "id": 1604,
        "name": "茂南区",
        "parentId": 16
    }, {
        "id": 1605,
        "name": "信宜市",
        "parentId": 16
    }]
}, {
    "id": 17,
    "name": "肇庆",
    "parentId": 0,
    "districts": [{
        "id": 1701,
        "name": "德庆县",
        "parentId": 17
    }, {
        "id": 1702,
        "name": "鼎湖区",
        "parentId": 17
    }, {
        "id": 1703,
        "name": "端州区",
        "parentId": 17
    }, {
        "id": 1704,
        "name": "封开县",
        "parentId": 17
    }, {
        "id": 1705,
        "name": "高要区",
        "parentId": 17
    }, {
        "id": 1706,
        "name": "广宁县",
        "parentId": 17
    }, {
        "id": 1707,
        "name": "怀集县",
        "parentId": 17
    }, {
        "id": 1708,
        "name": "四会市",
        "parentId": 17
    }, {
        "id": 1709,
        "name": "高新技术产业开发区",
        "parentId": 17
    }]
}, {
    "id": 18,
    "name": "清远",
    "parentId": 0,
    "districts": [{
        "id": 1801,
        "name": "佛冈县",
        "parentId": 18
    }, {
        "id": 1802,
        "name": "连南瑶族自治县",
        "parentId": 18
    }, {
        "id": 1803,
        "name": "连山壮族瑶族自治县",
        "parentId": 18
    }, {
        "id": 1804,
        "name": "连州市",
        "parentId": 18
    }, {
        "id": 1805,
        "name": "清城区",
        "parentId": 18
    }, {
        "id": 1806,
        "name": "清新区",
        "parentId": 18
    }, {
        "id": 1807,
        "name": "阳山县",
        "parentId": 18
    }, {
        "id": 1808,
        "name": "英德市",
        "parentId": 18
    }]
}, {
    "id": 19,
    "name": "潮州",
    "parentId": 0,
    "districts": [{
        "id": 1901,
        "name": "潮安区",
        "parentId": 19
    }, {
        "id": 1902,
        "name": "饶平县",
        "parentId": 19
    }, {
        "id": 1903,
        "name": "湘桥区",
        "parentId": 19
    }]
}, {
    "id": 20,
    "name": "揭阳",
    "parentId": 0,
    "districts": [{
        "id": 2001,
        "name": "惠来县",
        "parentId": 20
    }, {
        "id": 2002,
        "name": "揭东区",
        "parentId": 20
    }, {
        "id": 2003,
        "name": "揭西县",
        "parentId": 20
    }, {
        "id": 2004,
        "name": "普宁市",
        "parentId": 20
    }, {
        "id": 2005,
        "name": "榕城区",
        "parentId": 20
    }, {
        "id": 2006,
        "name": "潮南区",
        "parentId": 20
    }]
}, {
    "id": 21,
    "name": "云浮",
    "parentId": 0,
    "districts": [{
        "id": 2101,
        "name": "罗定市",
        "parentId": 21
    }, {
        "id": 2102,
        "name": "新兴县",
        "parentId": 21
    }, {
        "id": 2103,
        "name": "郁南县",
        "parentId": 21
    }, {
        "id": 2104,
        "name": "云安区",
        "parentId": 21
    }, {
        "id": 2105,
        "name": "云城区",
        "parentId": 21
    }]
}];
export default{
    gdCityDistrictList
};